"""Add study checklist items

Revision ID: 044540405e3c
Revises: 9b10b203155c
Create Date: 2026-08-11 10:01:57.665697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '044540405e3c'
down_revision: Union[str, Sequence[str], None] = '9b10b203155c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['study_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_checklist_items_id'), 'study_checklist_items', ['id'], unique=False)
    op.add_column('study_goals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('study_goals', 'ccreated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_goals', sa.Column('ccreated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('study_goals', 'created_at')
    op.drop_index(op.f('ix_study_checklist_items_id'), table_name='study_checklist_items')
    op.drop_table('study_checklist_items')
    # ### end Alembic commands ###
